name: tinder_clone
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

    # 画面サイズを調節できるプラグイン
    # https://pub.dev/packages/flutter_screenutil
  flutter_screenutil: ^1.1.0

  # Font Awesomeを使えるプラグイン
  # https://pub.dev/packages/font_awesome_flutter
  font_awesome_flutter: ^8.7.0
  
  # チャット用のプラグイン　
  # https://pub.dev/packages/bubble
  bubble: ^1.1.9+1

  # 無限スクロールとかできるようにするプラグイン
  # https://pub.dev/packages/carousel_slider
  carousel_slider: ^1.4.1

  # クパチーノのアイコン追加するプラグイン
  # https://pub.dev/packages/cupertino_icons
  cupertino_icons: ^0.1.2

  # ティンダースワイププラグイン
  # https://pub.dev/packages/flutter_tindercard
  flutter_tindercard: ^0.1.8


dev_dependencies:
  flutter_test:
    sdk: flutter
  


flutter:
  uses-material-design: true

  assets:
    - assets/images/
  
  fonts:
    - family: Tinder_clone
      fonts:
        - asset: assets/fonts/Tinder_clone.ttf
